collections:
  research:
    output: true
    permalink: /research_pages/:path/
  projects:
    output: true
    permalink: /project_pages/:path/
  publications:
    output: true
    permalink: /publications/:path/

name: Nathan Mitchell's Website

exclude: [vendor]
